// kinetic_wasm -- the machine's own motion planner behind a C ABI: the board's
// MotionArbiter and its engine, fed 0x2101 segments in wire units and stepped
// on a fixed tick against an ideal emitter, for an offline renderer
// Constraints:
// - THE PLANNER IS THE BOARD'S: kinetic2::Engine<1> inside MotionArbiter.
//   kinetic_version() names it.
// - NO PLANNING LIVES HERE. The shaping is ../Kinetic (include/kinetic2), the
//   intent path is flagship_p4/src/motion/MotionArbiter.cpp, the wire decode
//   is flagship_p4/src/motion/StreamIntent.h, the emitter is
//   sim/valencesim/src/IdealEmitter.h: every one compiled verbatim, the same
//   sources the P4 links. This file is plumbing: the clock, the tick order and
//   the ABI structs. A planning rule written here is one the machine does not
//   run.
// - DETERMINISTIC: an integer microsecond clock owned by the handle, no wall
//   clock, no randomness. Same calls in, same bits out, on every IEEE-754 host
//   built without FP contraction (README.md).
// - The gates are opened once at create (powered, commissioned, homed at
//   0 mm) and never exposed: e-stop, pause, override and ownership are the
//   hub's, not a renderer's.
// - SINGLE-THREADED per handle. One handle is one machine.
// See: README.md (units, field order, the pin rule), SPEC 5.4, SPEC 9.6

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <initializer_list>
#include <new>

#include "../../sim/valencesim/src/IdealEmitter.h"
#include "geiger/geiger.h"
#include "motion/MotionArbiter.h"
#include "motion/StreamIntent.h"
#include "motion/ValenceMotion.h"
#include "valence/generated/registry_constants.hpp"

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#define KINETIC_API extern "C" EMSCRIPTEN_KEEPALIVE
#else
#define KINETIC_API extern "C"
#endif

// Generated by the wasm build (CMakeLists.txt script mode); absent natively.
#if __has_include("kinetic_git_sha.h")
#include "kinetic_git_sha.h"
#endif
#ifndef NUCLEUS_GIT_SHA
#define NUCLEUS_GIT_SHA "native"
#endif

// ---- the ABI structs --------------------------------------------------------
// Fixed layouts, no padding, little-endian (wasm32 and every host this runs
// on). A field is only ever appended; README.md is the reader's map.

extern "C" {

// One evaluated tick. Engine frame = the travel window normalized to 0..1.
struct kinetic_sample {
    double   t_us;           // engine clock at this sample, microseconds
    double   p;              // plan position, engine frame, UNCLAMPED (the engine's float, widened)
    double   v;              // plan velocity, engine frame units/s
    double   a;              // plan acceleration, engine frame units/s^2
    float    plan_mm;        // plan position as the census publishes it: window-clamped, mm
    float    velocity_mm_s;  // census plan velocity, mm/s
    float    accel_mm_s2;    // a times the window span, mm/s^2 (UNCLAMPED, the census has no accel)
    float    position_mm;    // the ideal emitter's count, mm: what an on-time LP core renders
    float    target_mm;      // where the active plan ends, mm
    uint32_t anomalies;      // bit k: kinetic2::AnomalyKind k was recorded since the previous step
    uint8_t  mode;           // MotionCensus::mode (README.md)
    uint8_t  plan_kind;      // MotionCensus::plan_kind (README.md)
    uint8_t  flags;          // KINETIC_FLAG_* below
    uint8_t  reserved;       // zero
    uint32_t plans;          // successful plans since create or reset
};

// MotionTuning (ValenceMotion.h) as a C struct, Kinetic²'s set (RFC-108
// item 7); the catalog's units. The offsets are ABI.
struct kinetic_tuning {
    float    jmax_ovr;          // normalized window units/s^3, 0 = derived from the mm limits
    float    vmax_ovr;          // normalized window units/s, 0 = derived
    float    amax_ovr;          // normalized window units/s^2, 0 = derived
    uint32_t chase_dense_us;    // ignored here: the samples grant's latency on the board
    uint32_t react_us;          // the reaction horizon
    float    smoothness;        // 0 crisp .. 1 smooth
    float    handle_floor;      // 0.05..0.33, share of the piece
    float    trim_max;          // 0.1..1, share of the window span
};

// One pending knot as the solver placed it, 40 bytes (the same layout as
// Kinetic's own kinetic2_knot). Read after kinetic_evaluate.
struct kinetic_knot {
    double   t_us;        // solved time (a corner's ramp end; a live jog may land later)
    float    p;           // engine frame, 0..1 of the window
    float    v;           // the junction velocity the solver chose or kept
    float    a;           // the junction acceleration
    float    share;       // the share of the stroke a trim kept, 1 = whole
    float    stretched_s; // a live jog's seconds past its time; else 0
    float    worst;       // the incoming piece's worst ceiling ratio after the trim
    uint8_t  dropped;     // always 0: a knot is never dropped
    uint8_t  clamped;     // an authored velocity was cut
    uint8_t  pin_v;       // always 0; ABI field
    uint8_t  pin_a;       // always 0; ABI field
    uint8_t  reserved[4]; // zero
};

}  // extern "C"

static_assert(sizeof(kinetic_sample) == 64, "kinetic_sample layout is ABI");
static_assert(sizeof(kinetic_knot) == 40 && offsetof(kinetic_knot, share) == 20 &&
                  offsetof(kinetic_knot, dropped) == 32,
              "kinetic_knot layout is ABI");
static_assert(offsetof(kinetic_sample, plan_mm) == 32 && offsetof(kinetic_sample, anomalies) == 52 &&
                  offsetof(kinetic_sample, mode) == 56 && offsetof(kinetic_sample, plans) == 60,
              "kinetic_sample layout is ABI");
static_assert(sizeof(kinetic_tuning) == 32 && offsetof(kinetic_tuning, chase_dense_us) == 12 &&
                  offsetof(kinetic_tuning, react_us) == 16 && offsetof(kinetic_tuning, smoothness) == 20 &&
                  offsetof(kinetic_tuning, handle_floor) == 24 && offsetof(kinetic_tuning, trim_max) == 28,
              "kinetic_tuning layout is ABI");

// kinetic_sample::flags
inline constexpr uint8_t KINETIC_FLAG_BUSY     = 1u << 0;  // the plan has motion left to render
inline constexpr uint8_t KINETIC_FLAG_SHAPED   = 1u << 1;  // a knot was trimmed toward its predecessor
inline constexpr uint8_t KINETIC_FLAG_CLAMPED  = 1u << 2;  // raw p is outside the window: the output backstop is acting
inline constexpr uint8_t KINETIC_FLAG_REFUSED  = 1u << 3;  // a submit since the previous step was refused

// Named, not anonymous: kinetic_handle (global, the ABI's) holds a Host.
namespace kinetic_wasm {

using valence::IdealEmitter;
using valence::MotionArbiter;
using valence::MotionCensus;
using valence::MotionTuning;
using AnomalyType = kinetic2::AnomalyKind;

constexpr uint32_t kindBit(AnomalyType k) { return 1u << uint8_t(k); }

constexpr uint32_t kShapedMask   = kindBit(AnomalyType::KnotTrimmed);
// PieceOverCeiling renders at its least-over trim: never in a mask here.
constexpr uint32_t kRefusedMask  = kindBit(AnomalyType::KnotRefused);
static_assert(valence::kAnomalyKinds <= 32, "the anomaly mask is one word");

// The window solve is timed against this clock for the census; offline that cost is
// meaningless, so it reads a constant and the plan-cost fields stay 0.
uint64_t zeroClock() { return 0; }

struct Params {
    float    vmax, amax, jmax, rail;
    float    lo, hi;
    uint32_t horizon_us;
    MotionTuning tuning;
};

// One machine. Heap-allocated per handle: the engine is KB-scale.
class Host {
public:
    // The arbiter holds a reference to _emitter: a Host is never copied or moved.
    explicit Host(const Params& p) : _params(p) {
        _emitter.advance(0);
        _arb.begin(0);
        _arb.setMotorPowered(true);
        _arb.setCommissioned(true);
        _arb.setInputLimits(p.vmax, p.amax, p.jmax);
        _arb.setWindow(p.lo, p.hi, p.rail);
        _arb.forceHome(p.rail);
        _arb.applyTuning(p.tuning);
        _anom = _arb.snapshot(0).anom;
    }

    const Params& params() const { return _params; }

    bool setWindow(float lo, float hi) {
        if (!(std::isfinite(lo) && std::isfinite(hi) && hi > lo && lo >= 0.0f && hi <= _params.rail))
            return false;
        _arb.setWindow(lo, hi, _params.rail);
        _params.lo = lo;
        _params.hi = hi;
        return true;
    }

    void setTuning(const MotionTuning& t) {
        _params.tuning = t;
        _arb.applyTuning(t);
    }

    // The hub's anchor rule (SPEC 5.4, ValenceDevice::onStreamBundle): a start
    // in the past is due now, one beyond the horizon is clamped to it.
    int submit(uint16_t pos_e4, uint16_t dur_ms, int16_t end_vel_e3, double start_us, bool supersede) {
        double lead = start_us - double(_now_us);
        if (!(lead > 0.0)) lead = 0.0;
        if (lead > double(_params.horizon_us)) lead = double(_params.horizon_us);
        const uint64_t anchor = _now_us + uint64_t(lead);
        auto in = valence::segmentIntent(pos_e4, dur_ms, end_vel_e3, _params.lo,
                                         _params.hi - _params.lo, anchor);
        if (!in) return -1;
        // RFC-087: the hub sets it on the first segment of a bundle the motion
        // path takes (ValenceDevice::onStreamBundle); the caller decides.
        in->supersede = supersede;
        if (_arb.accept(*in, _now_us)) return 1;
        _refused = true;
        return 0;
    }

    // A Manual point (the jog): held inside the window, planned at the jog
    // set, live (the newest target supersedes the queue). No override here:
    // the gates are the hub's.
    int submitManual(float target_mm) {
        valence::MotionIntent in;
        in.source    = valence::MotionSource::Manual;
        in.target_mm = target_mm;
        if (_arb.accept(in, _now_us)) return 1;
        _refused = true;
        return 0;
    }

    uint32_t pending() { return uint32_t(_arb.engine().pending(0)); }

    int solved(uint32_t i, kinetic_knot& out) {
        auto& e = _arb.engine();
        if (i >= e.pending(0)) return 0;
        const kinetic2::Solved& s = e.solved(0, i);
        std::memset(&out, 0, sizeof(out));
        out.t_us        = double(s.t_us);
        out.p           = s.p;
        out.v           = s.v;
        out.a           = s.a;
        out.share       = s.share;
        out.stretched_s = s.stretched_s;
        out.worst       = s.worst;
        out.dropped     = s.dropped ? 1 : 0;
        out.clamped     = s.clamped ? 1 : 0;
        out.pin_v       = s.pin_v ? 1 : 0;
        out.pin_a       = s.pin_a ? 1 : 0;
        return 1;
    }

    // The board's wake order (ValenceMotion.cpp MotionTask::run): the clock
    // reads, the queued intents are accepted at that reading, then the tick
    // evaluates. advance() is the clock; a submit between is an intent that
    // woke the task; evaluate() is the tick: the emitter has rendered up to
    // now, then evaluate, then the census. step() is both for a caller whose
    // intents ride the tick.
    void advance(double dt_s) {
        const double whole_us = std::round(dt_s * 1e6);
        if (whole_us > 0.0) _now_us += uint64_t(whole_us);
    }

    void step(double dt_s, kinetic_sample& out) {
        advance(dt_s);
        evaluate(out);
    }

    void evaluate(kinetic_sample& out) {
        _emitter.advance(_now_us);
        const float dt_f = float(_now_us - _prev_us) * 1e-6f;
        if (dt_f > 0.0f) {
            _prev_us = _now_us;
            _arb.evaluate(_now_us, dt_f);
        }
        _arb.drainAnomalies();
        const MotionCensus c = _arb.snapshot(_now_us);

        uint32_t mask = 0;
        for (uint8_t k = 0; k < valence::kAnomalyKinds; ++k)
            if (c.anom[k] != _anom[k]) mask |= 1u << k;
        _anom = c.anom;

        // The engine is float throughout: p, v and a are its own floats, widened.
        // Its frame is the window, 0..1.
        const kinetic2::State st = _arb.planState(_now_us);
        const double p = st.p, v = st.v, a = st.a;
        const double lo = 0.0, hi = 1.0;

        uint8_t flags = 0;
        if (c.busy) flags |= KINETIC_FLAG_BUSY;
        if (mask & kShapedMask) flags |= KINETIC_FLAG_SHAPED;
        if (p < lo || p > hi) flags |= KINETIC_FLAG_CLAMPED;
        if (_refused || (mask & kRefusedMask)) flags |= KINETIC_FLAG_REFUSED;
        _refused = false;

        std::memset(&out, 0, sizeof(out));
        out.t_us          = double(_now_us);
        out.p             = p;
        out.v             = v;
        out.a             = a;
        out.plan_mm       = c.plan_mm;
        out.velocity_mm_s = c.velocity_mm_s;
        out.accel_mm_s2   = float(a) * (_params.hi - _params.lo);
        out.position_mm   = c.position_mm;
        out.target_mm     = c.target_mm;
        out.anomalies     = mask;
        out.mode          = c.mode;
        out.plan_kind     = c.plan_kind;
        out.flags         = flags;
        out.plans         = c.plans;
    }

    double nowUs() const { return double(_now_us); }

    Host(const Host&) = delete;
    Host& operator=(const Host&) = delete;

private:
    Params _params;
    // Declaration order is construction order: the arbiter binds the emitter.
    IdealEmitter  _emitter;
    MotionArbiter _arb{_emitter, &zeroClock};
    uint64_t _now_us  = 0;
    uint64_t _prev_us = 0;
    bool     _refused = false;
    std::array<uint32_t, valence::kAnomalyKinds> _anom{};
};

MotionTuning fromC(const kinetic_tuning& t) {
    MotionTuning m;
    m.jmax_ovr       = t.jmax_ovr;
    m.vmax_ovr       = t.vmax_ovr;
    m.amax_ovr       = t.amax_ovr;
    m.chase_dense_us = t.chase_dense_us;
    m.react_us       = t.react_us;
    m.smoothness     = t.smoothness;
    m.handle_floor   = t.handle_floor;
    m.trim_max       = t.trim_max;
    return m;
}

kinetic_tuning toC(const MotionTuning& m) {
    kinetic_tuning t;
    std::memset(&t, 0, sizeof(t));
    t.jmax_ovr       = m.jmax_ovr;
    t.vmax_ovr       = m.vmax_ovr;
    t.amax_ovr       = m.amax_ovr;
    t.chase_dense_us = m.chase_dense_us;
    t.react_us       = m.react_us;
    t.smoothness     = m.smoothness;
    t.handle_floor   = m.handle_floor;
    t.trim_max       = m.trim_max;
    return t;
}

bool positive(float x) { return std::isfinite(x) && x > 0.0f; }

}  // namespace kinetic_wasm

using kinetic_wasm::Host;
using kinetic_wasm::Params;

// ---- the C ABI --------------------------------------------------------------

struct kinetic_handle {
    explicit kinetic_handle(const Params& p) : host(p) {}
    Host host;
};

// Null when a limit is non-finite or not positive. horizon_ms 0 is the
// protocol default (registry max_future_schedule_ms).
KINETIC_API kinetic_handle* kinetic_create(float vmax_mm_s, float amax_mm_s2, float jmax_mm_s3,
                                           float rail_mm, uint32_t horizon_ms) {
    using kinetic_wasm::positive;
    if (!(positive(vmax_mm_s) && positive(amax_mm_s2) && positive(jmax_mm_s3) && positive(rail_mm)))
        return nullptr;
    const uint32_t h_ms = horizon_ms != 0 ? horizon_ms : uint32_t(valence::limits::max_future_schedule_ms);
    const Params p{vmax_mm_s, amax_mm_s2, jmax_mm_s3, rail_mm, 0.0f, rail_mm, h_ms * 1000u,
                   valence::motionDefaultTuning()};
    return new (std::nothrow) kinetic_handle(p);
}

KINETIC_API void kinetic_destroy(kinetic_handle* h) { delete h; }

// Back to the create state at t = 0, keeping the limits, the window and the
// tuning. In-place destroy plus placement-new (cpp-safety.md T1).
KINETIC_API void kinetic_reset(kinetic_handle* h) {
    if (h == nullptr) return;
    const Params p = h->host.params();
    h->host.~Host();
    new (&h->host) Host(p);
}

// 1 applied, 0 refused (non-finite, hi <= lo, or outside 0..rail). Takes
// effect as the board's does: the next tick parks and reseeds at rest.
KINETIC_API int kinetic_set_window(kinetic_handle* h, float lo_mm, float hi_mm) {
    return h != nullptr && h->host.setWindow(lo_mm, hi_mm) ? 1 : 0;
}

KINETIC_API void kinetic_default_tuning(kinetic_tuning* out) {
    if (out != nullptr) *out = kinetic_wasm::toC(valence::motionDefaultTuning());
}

// Applied at once, as the board applies a tuning set before the next intent.
KINETIC_API void kinetic_set_tuning(kinetic_handle* h, const kinetic_tuning* t) {
    if (h != nullptr && t != nullptr) h->host.setTuning(kinetic_wasm::fromC(*t));
}

// One 0x2101 sample, wire units: pos_e4 1e-4 of the window, dur_ms, end_vel_e3
// 1e-3 window/s (-32768 = unspecified), start_us the segment's start on the
// engine clock. Planned at the current clock, before the next step. 1
// accepted, 0 refused by the planner, -1 zero duration (dropped, as the hub
// drops it).
KINETIC_API int kinetic_submit_segment(kinetic_handle* h, uint16_t pos_e4, uint16_t dur_ms,
                                       int16_t end_vel_e3, double start_us) {
    if (h == nullptr) return 0;
    return h->host.submit(pos_e4, dur_ms, end_vel_e3, start_us, false);
}

// kinetic_submit_segment with the RFC-087 supersede flag: nonzero on the first
// segment of a bundle flushes every knot queued at or after its start, as the
// hub does (ValenceDevice::onStreamBundle).
KINETIC_API int kinetic_submit_segment2(kinetic_handle* h, uint16_t pos_e4, uint16_t dur_ms,
                                        int16_t end_vel_e3, double start_us, uint8_t supersede) {
    if (h == nullptr) return 0;
    return h->host.submit(pos_e4, dur_ms, end_vel_e3, start_us, supersede != 0);
}

// A Manual point, mm: the jog as the hub submits it (window-held, jog set,
// live). 1 accepted, 0 refused.
KINETIC_API int kinetic_submit_manual(kinetic_handle* h, float target_mm) {
    if (h == nullptr) return 0;
    return h->host.submitManual(target_mm);
}

// kinetic_step in the board's wake order: kinetic_advance moves the clock by
// dt_s, the caller submits what arrived by then, kinetic_evaluate ticks.
KINETIC_API void kinetic_advance(kinetic_handle* h, double dt_s) {
    if (h != nullptr) h->host.advance(dt_s);
}

KINETIC_API void kinetic_evaluate(kinetic_handle* h, kinetic_sample* out) {
    if (h == nullptr || out == nullptr) return;
    h->host.evaluate(*out);
}

// Knots still ahead on the timeline and the i-th as the solver placed it.
// Read after kinetic_evaluate (a read between a submit and the tick solves
// early). 1 written, 0 when i is out of range.
KINETIC_API uint32_t kinetic_pending(kinetic_handle* h) { return h != nullptr ? h->host.pending() : 0; }

KINETIC_API int kinetic_solved(kinetic_handle* h, uint32_t i, kinetic_knot* out) {
    if (h == nullptr || out == nullptr) return 0;
    return h->host.solved(i, *out);
}

// Advances the clock by dt_s (rounded to whole microseconds) and evaluates.
KINETIC_API void kinetic_step(kinetic_handle* h, double dt_s, kinetic_sample* out) {
    if (h == nullptr || out == nullptr) return;
    h->host.step(dt_s, *out);
}

KINETIC_API double kinetic_now_us(const kinetic_handle* h) { return h != nullptr ? h->host.nowUs() : 0.0; }

// "nucleus <git sha> kinetic2 <engine version>". Static storage.
KINETIC_API const char* kinetic_version() {
    constexpr const char* kKernel = " kinetic2 ";
    constexpr const char* kKernelVersion = kinetic2::kVersion;
    static char buf[96] = {};
    if (buf[0] == '\0') {
        size_t n = 0;
        for (const char* part : {"nucleus ", NUCLEUS_GIT_SHA, kKernel, kKernelVersion})
            for (; *part != '\0' && n + 1 < sizeof(buf); ++part) buf[n++] = *part;
    }
    return buf;
}
