// kinetic_wasm -- the machine's own motion planner behind a C ABI: the board's
// MotionArbiter and its engine, fed 0x2101 segments in wire units and stepped
// on a fixed tick against an ideal emitter, for an offline renderer
// Constraints:
// - THE KERNEL IS THE BOARD'S BUILD SWITCH (NUCLEUS_KINETIC2, ValenceMotion.h):
//   kinetic::Engine by default, kinetic2::Engine<1> with the CMake option on.
//   kinetic_version() names which; the ABI differs only where README.md says.
// - NO PLANNING LIVES HERE. The shaping is ../Kinetic (engine + Ruckig), the
//   intent path is flagship_p4/src/motion/MotionArbiter.cpp, the wire decode
//   is flagship_p4/src/motion/StreamIntent.h, the emitter is
//   sim/valencesim/src/IdealEmitter.h: every one compiled verbatim, the same
//   sources the P4 links. This file is plumbing: the clock, the tick order and
//   the ABI structs. A planning rule written here is one the machine does not
//   run.
// - DETERMINISTIC: an integer microsecond clock owned by the handle, no wall
//   clock, no randomness. Same calls in, same bits out, on every IEEE-754 host
//   built without FP contraction (README.md).
// - The gates are opened once at create (powered, commissioned, homed at
//   0 mm) and never exposed: e-stop, pause, override and ownership are the
//   hub's, not a renderer's.
// - SINGLE-THREADED per handle. One handle is one machine.
// See: README.md (units, field order, the pin rule), SPEC 5.4, SPEC 9.6

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <initializer_list>
#include <new>

#include "../../sim/valencesim/src/IdealEmitter.h"
#include "geiger/geiger.h"
#include "motion/MotionArbiter.h"
#include "motion/StreamIntent.h"
#include "motion/ValenceMotion.h"
#include "valence/generated/registry_constants.hpp"

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#define KINETIC_API extern "C" EMSCRIPTEN_KEEPALIVE
#else
#define KINETIC_API extern "C"
#endif

// Generated by the wasm build (CMakeLists.txt script mode); absent natively.
#if __has_include("kinetic_git_sha.h")
#include "kinetic_git_sha.h"
#endif
#ifndef NUCLEUS_GIT_SHA
#define NUCLEUS_GIT_SHA "native"
#endif

// ---- the ABI structs --------------------------------------------------------
// Fixed layouts, no padding, little-endian (wasm32 and every host this runs
// on). A field is only ever appended; README.md is the reader's map.

extern "C" {

// One evaluated tick. Engine frame = the travel window normalized to 0..1.
struct kinetic_sample {
    double   t_us;           // engine clock at this sample, microseconds
    double   p;              // plan position, engine frame, UNCLAMPED (the double the engine evaluates)
    double   v;              // plan velocity, engine frame units/s
    double   a;              // plan acceleration, engine frame units/s^2
    float    plan_mm;        // plan position as the census publishes it: window-clamped, mm
    float    velocity_mm_s;  // census plan velocity, mm/s
    float    accel_mm_s2;    // a times the window span, mm/s^2 (UNCLAMPED, the census has no accel)
    float    position_mm;    // the ideal emitter's count, mm: what an on-time LP core renders
    float    target_mm;      // where the active plan ends, mm
    uint32_t anomalies;      // bit k: kinetic::AnomalyType k was recorded since the previous step
    uint8_t  mode;           // kinetic::Mode
    uint8_t  plan_kind;      // kinetic::PlanKind
    uint8_t  flags;          // KINETIC_FLAG_* below
    uint8_t  reserved;       // zero
    uint32_t plans;          // successful plans since create or reset
};

// MotionTuning (ValenceMotion.h) as a C struct; the catalog's units.
struct kinetic_tuning {
    float    jmax_ovr;          // normalized window units/s^3, 0 = derived from the mm limits
    float    vmax_ovr;          // normalized window units/s, 0 = derived
    float    amax_ovr;          // normalized window units/s^2, 0 = derived
    float    chase_gain;
    float    chase_lookahead;   // stream intervals
    float    handoff_k;         // RFC-008 chord factor, 0 = guard off
    float    smooth_budget;     // 0..1
    float    amplitude_budget;  // 0..1
    float    overshoot_guard;   // 0 = disarmed
    uint32_t chase_dense_us;
    uint32_t settle_grace_us;
    uint8_t  chase_ff;          // bool
    uint8_t  chase_accel_ff;    // bool
    uint8_t  chase_aim_extrap;  // bool
    uint8_t  curve_policy;      // 0 follow, 1 C1, 2 C2
    uint8_t  infeasible_policy; // 0 stretch, 1 blend
    uint8_t  blend_steps;
    uint8_t  reserved[2];       // zero
#if NUCLEUS_KINETIC2
    // Appended for Kinetic²'s planner options; a Kinetic build stops above.
    uint32_t lookahead_us;      // the solver's lookahead window
    uint8_t  corner;            // 0 continuous, 1 cubic
    uint8_t  reserved2[3];      // zero
#endif
};

}  // extern "C"

static_assert(sizeof(kinetic_sample) == 64, "kinetic_sample layout is ABI");
static_assert(offsetof(kinetic_sample, plan_mm) == 32 && offsetof(kinetic_sample, anomalies) == 52 &&
                  offsetof(kinetic_sample, mode) == 56 && offsetof(kinetic_sample, plans) == 60,
              "kinetic_sample layout is ABI");
static_assert(sizeof(kinetic_tuning) == (valence::kKinetic2 ? 60 : 52), "kinetic_tuning layout is ABI");

// kinetic_sample::flags
inline constexpr uint8_t KINETIC_FLAG_BUSY     = 1u << 0;  // the plan has motion left to render
inline constexpr uint8_t KINETIC_FLAG_SHAPED   = 1u << 1;  // a deadline was held by spending amplitude or shape (Blend)
inline constexpr uint8_t KINETIC_FLAG_FALLBACK = 1u << 2;  // the Ruckig guard took a segment (Kinetic only), or a deadline stretched
inline constexpr uint8_t KINETIC_FLAG_CLAMPED  = 1u << 3;  // raw p is outside the window: the output backstop is acting
inline constexpr uint8_t KINETIC_FLAG_REFUSED  = 1u << 4;  // a submit since the previous step was refused

// Named, not anonymous: kinetic_handle (global, the ABI's) holds a Host.
namespace kinetic_wasm {

using valence::IdealEmitter;
using valence::MotionArbiter;
using valence::MotionCensus;
using valence::MotionTuning;
#if NUCLEUS_KINETIC2
using AnomalyType = kinetic2::AnomalyKind;
#else
using kinetic::AnomalyType;
#endif

constexpr uint32_t kindBit(AnomalyType k) { return 1u << uint8_t(k); }

constexpr uint32_t kShapedMask   = kindBit(AnomalyType::WaveformScaled) | kindBit(AnomalyType::WaveformSmoothed);
constexpr uint32_t kFallbackMask = kindBit(AnomalyType::WaveformFallback) | kindBit(AnomalyType::DeadlineStretched);
#if NUCLEUS_KINETIC2
constexpr uint32_t kRefusedMask  = kindBit(AnomalyType::PlanFailed) | kindBit(AnomalyType::KnotRefused);
#else
constexpr uint32_t kRefusedMask  = kindBit(AnomalyType::PlanFailed);
#endif
static_assert(valence::kAnomalyKinds <= 32, "the anomaly mask is one word");

// commit() is timed against this clock for the census; offline that cost is
// meaningless, so it reads a constant and the plan-cost fields stay 0.
uint64_t zeroClock() { return 0; }

struct Params {
    float    vmax, amax, jmax, rail;
    float    lo, hi;
    uint32_t horizon_us;
    MotionTuning tuning;
};

// One machine. Heap-allocated per handle: the engine is KB-scale.
class Host {
public:
    // The arbiter holds a reference to _emitter: a Host is never copied or moved.
    explicit Host(const Params& p) : _params(p) {
        _emitter.advance(0);
        _arb.begin(0);
        _arb.setMotorPowered(true);
        _arb.setCommissioned(true);
        _arb.setInputLimits(p.vmax, p.amax, p.jmax);
        _arb.setWindow(p.lo, p.hi, p.rail);
        _arb.forceHome(p.rail);
        _arb.applyTuning(p.tuning);
        _anom = _arb.snapshot(0).anom;
    }

    const Params& params() const { return _params; }

    bool setWindow(float lo, float hi) {
        if (!(std::isfinite(lo) && std::isfinite(hi) && hi > lo && lo >= 0.0f && hi <= _params.rail))
            return false;
        _arb.setWindow(lo, hi, _params.rail);
        _params.lo = lo;
        _params.hi = hi;
        return true;
    }

    void setTuning(const MotionTuning& t) {
        _params.tuning = t;
        _arb.applyTuning(t);
    }

    // The hub's anchor rule (SPEC 5.4, ValenceDevice::onStreamBundle): a start
    // in the past is due now, one beyond the horizon is clamped to it.
    int submit(uint16_t pos_e4, uint16_t dur_ms, int16_t end_vel_e3, double start_us, uint8_t family) {
        double lead = start_us - double(_now_us);
        if (!(lead > 0.0)) lead = 0.0;
        if (lead > double(_params.horizon_us)) lead = double(_params.horizon_us);
        const uint64_t anchor = _now_us + uint64_t(lead);
        const auto in = valence::segmentIntent(pos_e4, dur_ms, end_vel_e3, _params.lo,
                                               _params.hi - _params.lo, family, anchor);
        if (!in) return -1;
        if (_arb.accept(*in, _now_us)) return 1;
        _refused = true;
        return 0;
    }

    // The board's tick order (ValenceMotion.cpp MotionTask::run): the emitter
    // has rendered up to now, then evaluate, then the census.
    void step(double dt_s, kinetic_sample& out) {
        const double whole_us = std::round(dt_s * 1e6);
        if (whole_us > 0.0) _now_us += uint64_t(whole_us);
        _emitter.advance(_now_us);
        const float dt_f = float(_now_us - _prev_us) * 1e-6f;
        if (dt_f > 0.0f) {
            _prev_us = _now_us;
            _arb.evaluate(_now_us, dt_f);
        }
        _arb.drainAnomalies();
        const MotionCensus c = _arb.snapshot(_now_us);

        uint32_t mask = 0;
        for (uint8_t k = 0; k < valence::kAnomalyKinds; ++k)
            if (c.anom[k] != _anom[k]) mask |= 1u << k;
        _anom = c.anom;

#if NUCLEUS_KINETIC2
        // Kinetic² is float throughout: p, v and a are its own floats, widened.
        // Its frame is the window, 0..1.
        const kinetic2::State st = _arb.planState(_now_us);
        const double p = st.p, v = st.v, a = st.a;
        const double lo = 0.0, hi = 1.0;
#else
        const kinetic::PlanView pv = _arb.engine().planView();
        double p = 0.0, v = 0.0, a = 0.0;
        kinetic::Engine::evalPiece(pv.active, _now_us, p, v, a);
        const double lo = pv.lo, hi = pv.hi;
#endif

        uint8_t flags = 0;
        if (c.busy) flags |= KINETIC_FLAG_BUSY;
        if (mask & kShapedMask) flags |= KINETIC_FLAG_SHAPED;
        if (mask & kFallbackMask) flags |= KINETIC_FLAG_FALLBACK;
        if (p < lo || p > hi) flags |= KINETIC_FLAG_CLAMPED;
        if (_refused || (mask & kRefusedMask)) flags |= KINETIC_FLAG_REFUSED;
        _refused = false;

        std::memset(&out, 0, sizeof(out));
        out.t_us          = double(_now_us);
        out.p             = p;
        out.v             = v;
        out.a             = a;
        out.plan_mm       = c.plan_mm;
        out.velocity_mm_s = c.velocity_mm_s;
        out.accel_mm_s2   = float(a) * (_params.hi - _params.lo);
        out.position_mm   = c.position_mm;
        out.target_mm     = c.target_mm;
        out.anomalies     = mask;
        out.mode          = c.mode;
        out.plan_kind     = c.plan_kind;
        out.flags         = flags;
        out.plans         = c.plans;
    }

    double nowUs() const { return double(_now_us); }

    Host(const Host&) = delete;
    Host& operator=(const Host&) = delete;

private:
    Params _params;
    // Declaration order is construction order: the arbiter binds the emitter.
    IdealEmitter  _emitter;
    MotionArbiter _arb{_emitter, &zeroClock};
    uint64_t _now_us  = 0;
    uint64_t _prev_us = 0;
    bool     _refused = false;
    std::array<uint32_t, valence::kAnomalyKinds> _anom{};
};

MotionTuning fromC(const kinetic_tuning& t) {
    MotionTuning m;
    m.jmax_ovr          = t.jmax_ovr;
    m.vmax_ovr          = t.vmax_ovr;
    m.amax_ovr          = t.amax_ovr;
    m.chase_ff          = t.chase_ff != 0;
    m.chase_accel_ff    = t.chase_accel_ff != 0;
    m.chase_gain        = t.chase_gain;
    m.chase_lookahead   = t.chase_lookahead;
    m.chase_dense_us    = t.chase_dense_us;
    m.chase_aim_extrap  = t.chase_aim_extrap != 0;
    m.handoff_k         = t.handoff_k;
    m.curve_policy      = t.curve_policy;
    m.infeasible_policy = t.infeasible_policy;
    m.smooth_budget     = t.smooth_budget;
    m.amplitude_budget  = t.amplitude_budget;
    m.blend_steps       = t.blend_steps;
    m.settle_grace_us   = t.settle_grace_us;
    m.overshoot_guard   = t.overshoot_guard;
#if NUCLEUS_KINETIC2
    m.lookahead_us      = t.lookahead_us;
    m.corner            = t.corner;
#endif
    return m;
}

kinetic_tuning toC(const MotionTuning& m) {
    kinetic_tuning t;
    std::memset(&t, 0, sizeof(t));
    t.jmax_ovr          = m.jmax_ovr;
    t.vmax_ovr          = m.vmax_ovr;
    t.amax_ovr          = m.amax_ovr;
    t.chase_gain        = m.chase_gain;
    t.chase_lookahead   = m.chase_lookahead;
    t.handoff_k         = m.handoff_k;
    t.smooth_budget     = m.smooth_budget;
    t.amplitude_budget  = m.amplitude_budget;
    t.overshoot_guard   = m.overshoot_guard;
    t.chase_dense_us    = m.chase_dense_us;
    t.settle_grace_us   = m.settle_grace_us;
    t.chase_ff          = m.chase_ff ? 1 : 0;
    t.chase_accel_ff    = m.chase_accel_ff ? 1 : 0;
    t.chase_aim_extrap  = m.chase_aim_extrap ? 1 : 0;
    t.curve_policy      = m.curve_policy;
    t.infeasible_policy = m.infeasible_policy;
    t.blend_steps       = m.blend_steps;
#if NUCLEUS_KINETIC2
    t.lookahead_us      = m.lookahead_us;
    t.corner            = m.corner;
#endif
    return t;
}

bool positive(float x) { return std::isfinite(x) && x > 0.0f; }

}  // namespace kinetic_wasm

using kinetic_wasm::Host;
using kinetic_wasm::Params;

// ---- the C ABI --------------------------------------------------------------

struct kinetic_handle {
    explicit kinetic_handle(const Params& p) : host(p) {}
    Host host;
};

// Null when a limit is non-finite or not positive. horizon_ms 0 is the
// protocol default (registry max_future_schedule_ms).
KINETIC_API kinetic_handle* kinetic_create(float vmax_mm_s, float amax_mm_s2, float jmax_mm_s3,
                                           float rail_mm, uint32_t horizon_ms) {
    using kinetic_wasm::positive;
    if (!(positive(vmax_mm_s) && positive(amax_mm_s2) && positive(jmax_mm_s3) && positive(rail_mm)))
        return nullptr;
    const uint32_t h_ms = horizon_ms != 0 ? horizon_ms : uint32_t(valence::limits::max_future_schedule_ms);
    const Params p{vmax_mm_s, amax_mm_s2, jmax_mm_s3, rail_mm, 0.0f, rail_mm, h_ms * 1000u,
                   valence::motionDefaultTuning()};
    return new (std::nothrow) kinetic_handle(p);
}

KINETIC_API void kinetic_destroy(kinetic_handle* h) { delete h; }

// Back to the create state at t = 0, keeping the limits, the window and the
// tuning. In-place destroy plus placement-new (cpp-safety.md T1).
KINETIC_API void kinetic_reset(kinetic_handle* h) {
    if (h == nullptr) return;
    const Params p = h->host.params();
    h->host.~Host();
    new (&h->host) Host(p);
}

// 1 applied, 0 refused (non-finite, hi <= lo, or outside 0..rail). Takes
// effect as the board's does: the next tick parks and reseeds at rest.
KINETIC_API int kinetic_set_window(kinetic_handle* h, float lo_mm, float hi_mm) {
    return h != nullptr && h->host.setWindow(lo_mm, hi_mm) ? 1 : 0;
}

KINETIC_API void kinetic_default_tuning(kinetic_tuning* out) {
    if (out != nullptr) *out = kinetic_wasm::toC(valence::motionDefaultTuning());
}

// Applied at once, as the board applies a tuning set before the next intent.
KINETIC_API void kinetic_set_tuning(kinetic_handle* h, const kinetic_tuning* t) {
    if (h != nullptr && t != nullptr) h->host.setTuning(kinetic_wasm::fromC(*t));
}

// One 0x2101 sample, wire units: pos_e4 1e-4 of the window, dur_ms, end_vel_e3
// 1e-3 window/s (-32768 = unspecified), start_us the segment's start on the
// engine clock, curve_family the GRANTED family (registry curve_families).
// Planned at the current clock, before the next step. 1 accepted, 0 refused by
// the planner, -1 zero duration (dropped, as the hub drops it).
KINETIC_API int kinetic_submit_segment(kinetic_handle* h, uint16_t pos_e4, uint16_t dur_ms,
                                       int16_t end_vel_e3, double start_us, uint8_t curve_family) {
    if (h == nullptr) return 0;
    return h->host.submit(pos_e4, dur_ms, end_vel_e3, start_us, curve_family);
}

// Advances the clock by dt_s (rounded to whole microseconds) and evaluates.
KINETIC_API void kinetic_step(kinetic_handle* h, double dt_s, kinetic_sample* out) {
    if (h == nullptr || out == nullptr) return;
    h->host.step(dt_s, *out);
}

KINETIC_API double kinetic_now_us(const kinetic_handle* h) { return h != nullptr ? h->host.nowUs() : 0.0; }

// "nucleus <git sha> kinetic <engine version>", or "... kinetic2 <engine
// version>" from a Kinetic² build. Static storage.
KINETIC_API const char* kinetic_version() {
#if NUCLEUS_KINETIC2
    constexpr const char* kKernel = " kinetic2 ";
    constexpr const char* kKernelVersion = kinetic2::kVersion;
#else
    constexpr const char* kKernel = " kinetic ";
    constexpr const char* kKernelVersion = kinetic::kVersion;
#endif
    static char buf[96] = {};
    if (buf[0] == '\0') {
        size_t n = 0;
        for (const char* part : {"nucleus ", NUCLEUS_GIT_SHA, kKernel, kKernelVersion})
            for (; *part != '\0' && n + 1 < sizeof(buf); ++part) buf[n++] = *part;
    }
    return buf;
}
